sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
services:
- docker
env:
  global:
    - HEROKU_APP=still-fortress-86423
script:
- docker build -t registry.heroku.com/$HEROKU_APP/web .
after_success:
  - docker push registry.heroku.com/$HEROKU_APP/web
  - heroku container:release web --app $HEROKU_APP
notifications:
  email: true
