sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
services:
- docker
before_install:
- docker build -t registry.heroku.com/still-fortress-86423/web .
script:
  - echo "skipping tests"
deploy:
  - provider: script
    script: bash deploy.sh
    on:
      branch: master
notifications:
  email: true
