sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
services:
- docker
script:
- docker-compose build
deploy:
  provider: heroku
  api_key:
    secure: T9XNQFZZHGTNh5rPcO+MLdT0RArGd8gOR5FmuN5ggLoLyNWY4qLB/4plA3yUQQoiZuWSj4GnYrnYZOYKXbwwjO37ivpb50HGNIyohy+bxVwXdYTsQcANjKoaQsj90/cnP/22etM2oExFMN3zue8VhqUVQmY4avYfRN/JsSxLMX5EOK45RopBgodVumqmC1S0H1GjBSEj9MGWPfHRYiBcFgAGT3Txmh7BcdPVn5SxYkd+DptYdbuxxsEBieMaGyJVQxSLIzoEKrSQozW4CMUJyh3NvIVahSWvOjbREO11Knwge68GGwAgBjdNoCpjgrGRT5QNLxLjNYb/hHGI9pnzJNNRsFPqEj2XfJFSUwq6LFKeVKpg34S6tOyiPuGlzCFXo4HuSils++wXs8ZWhymh/f/tfF3mhMx7dItyjSSCPOGODe6nRtzq4MaOqAvfkuVD9ltN0/+0LDq5a1fBDTtZ4zstQsBzxf4+v4OZLPMokt8DJQQ4Cg847O71lcbkR18npT2wbkM1AhLssftqagaqPUA72aOggsXYr7RPF4OkDmY4Tkfklo5Dd92lSmBN6drJO2l5nxPSTQJvJ1WVUuu6C48Zu6+M1pTm6Hjsfcp3UySJ7In5iRQN7mqVodT2OyvGwXfjeheK2N4o2r1bBQBVU1DrgPYaBlEOQ+kBdHdpX4E=
  on:
    tags: true
    all_branches: true
notifications:
  email: true
