sudo: required
language: node_js
node_js:
- '8'
cache:
  directories:
  - "~/.npm"
  - "~/.cache"
services:
- docker
env:
  global:
    - HEROKU_APP=still-fortress-86423
script:
- docker build -t registry.heroku.com/$HEROKU_APP/web .
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
notifications:
  email: true
