version: '3.7'

services:
  server:
    build: ./server
    volumes:
    - ./server:/app
    ports:
    - 5000:5000
    restart: unless-stopped
    environment:
      FLASK_DEV: development
      PYTHONUNBUFFERED: 1
    container_name: registry.heroku.com/still-fortress-86423/web
  client:
    build: ./client
    volumes:
    - ./client:/app
    - /app/node_modules
    ports:
    - 8080:8080
    links:
      - server
    depends_on:
      - server