version: '3.7'

services:
  server:
    build: ./server
    command: python run.py
    volumes:
    - ./server:/app
    ports:
    - 5000:5000
    restart: unless-stopped
    env_file:
      - ./.dev.env
  web:
    build: ./client
    volumes:
    - ./client:/app
    - /app/node_modules
    ports:
    - 8080:8080
    links:
      - server
    depends_on:
      - server